services:
  educhatbot-postgres:
    image: pgvector/pgvector:pg16
    container_name: educhatbot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: educhatbotdb
    ports:
      - "5433:5432"
    volumes:
      - educhatbot_postgres_data:/var/lib/postgresql/data

volumes:
  educhatbot_postgres_data:
