// <auto-generated />
using EduChatbot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EduChatbot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604090000_AddDocumentReviewWorkflow")]
    partial class AddDocumentReviewWorkflow
    {
    }
}
